# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DMA_Controller_0_0/design_1_DMA_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DMA_Controller_0_0 || ORIG_REF_NAME==design_1_DMA_Controller_0_0} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_DMA_Controller_0_0/src/fifo_dataout/fifo_dataout.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_dataout || ORIG_REF_NAME==fifo_dataout} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_DMA_Controller_0_0/src/fifo_data/fifo_data.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_data || ORIG_REF_NAME==fifo_data} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Accelerator_0_0/design_1_Accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Accelerator_0_0 || ORIG_REF_NAME==design_1_Accelerator_0_0} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/shift_ram_1/shift_ram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==shift_ram_1 || ORIG_REF_NAME==shift_ram_1} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/bram_layer2/bram_layer2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_layer2 || ORIG_REF_NAME==bram_layer2} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/accum/accum.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accum || ORIG_REF_NAME==accum} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/ROM_bias/ROM_bias.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_bias || ORIG_REF_NAME==ROM_bias} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/bram_fcweight/bram_fcweight.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_fcweight || ORIG_REF_NAME==bram_fcweight} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/fifo_FClayer/fifo_FClayer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_FClayer || ORIG_REF_NAME==fifo_FClayer} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/multiplier_fc/multiplier_fc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiplier_fc || ORIG_REF_NAME==multiplier_fc} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/shift_ram/shift_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==shift_ram || ORIG_REF_NAME==shift_ram} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/adder/adder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/pooling_shift_1/pooling_shift_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pooling_shift_1 || ORIG_REF_NAME==pooling_shift_1} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/ROM_weight/ROM_weight.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_weight || ORIG_REF_NAME==ROM_weight} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/RAM_ip/RAM_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_ip || ORIG_REF_NAME==RAM_ip} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/ROM_data/ROM_data.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_data || ORIG_REF_NAME==ROM_data} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/pooling_shift/pooling_shift.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pooling_shift || ORIG_REF_NAME==pooling_shift} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/multiplier/multiplier.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet

# IP: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_0/design_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_1/design_1_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_1 || ORIG_REF_NAME==design_1_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_DMA_Controller_0_0/src/fifo_dataout/fifo_dataout.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_dataout || ORIG_REF_NAME==fifo_dataout} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_DMA_Controller_0_0/src/fifo_data/fifo_data.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_data || ORIG_REF_NAME==fifo_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/bram_layer2/bram_layer2_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/ROM_bias/ROM_bias_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/bram_fcweight/bram_fcweight_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/fifo_FClayer/fifo_FClayer.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_FClayer || ORIG_REF_NAME==fifo_FClayer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/ROM_weight/ROM_weight_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/RAM_ip/RAM_ip_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/ROM_data/ROM_data_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_0_0/src/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc

# XDC: c:/Users/zhengzb/Desktop/project/kv260/lenet_kv260/lenet_kv260.gen/sources_1/bd/design_1/design_1_ooc.xdc
