#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Jul 29 15:43:53 +0200 2024
# SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_13 zynq_ultra_ps_e_vip_v1_0_13 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_27 fifo_generator_v13_2_7 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 axi_protocol_converter_v2_1_27 axi_clock_converter_v2_1_26 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_27 xbip_utils_v3_0_10 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 c_reg_fd_v12_0_6 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 dist_mem_gen_v8_0_13 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 xbip_dsp48_acc_v3_0_6 xbip_accum_v3_0_6 c_accum_v12_0_14)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "D:/vivado2022.2/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/vivado2022.2/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/vivado2022.2/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_99M_0/sim/design_1_rst_ps8_0_99M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_2/sim/design_1_xbar_2.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/4675/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_0/sim/design_1_auto_us_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_1/sim/design_1_auto_us_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/fifo_generator_0/sim/fifo_generator_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/multiplier/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/multiplier/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/multiplier/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_18 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/multiplier/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/multiplier/sim/multiplier.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/pooling_shift/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/pooling_shift/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/pooling_shift/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/pooling_shift/sim/pooling_shift.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/ROM_data/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/ROM_data/sim/ROM_data.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/RAM_ip/sim/RAM_ip.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/ROM_weight/sim/ROM_weight.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/pooling_shift_1/sim/pooling_shift_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/adder/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/adder/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/adder/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/adder/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/adder/sim/adder.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/shift_ram/sim/shift_ram.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/multiplier_fc/sim/multiplier_fc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/fifo_FClayer/sim/fifo_FClayer.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/bram_fcweight/sim/bram_fcweight.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/ROM_bias/sim/ROM_bias.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_dsp48_acc_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/accum/hdl/xbip_dsp48_acc_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_accum_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/accum/hdl/xbip_accum_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_accum_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ip/design_1_Accelerator_1_0/src/accum/hdl/c_accum_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/accum/sim/accum.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/bram_layer2/sim/bram_layer2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/src/shift_ram_1/sim/shift_ram_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/df45/src" +incdir+"$ref_dir/../../../../lenet_kv260.gen/sources_1/bd/design_1/ipshared/df45/src" +incdir+"D:/vivado2022.2/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Acc_Controller.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Bias_input.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/ConvPE.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/ConvPE_list.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Layer_buffer.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Relu_MaxPooling.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Relu_MaxPooling_list.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Win_input.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/adder.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/adderTree.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/dataCorrect.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/dataShift.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/multMatrix.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/multiplier.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/weightShift.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Conv_layer.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/FClayer_buffer.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Multiplier_List.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/FC_layer.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/multiplier_fc.v" \
    "$ref_dir/../../../bd/design_1/ipshared/65d0/src/Accelerator.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Accelerator_1_0/sim/design_1_Accelerator_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_DMA_Controller_0_1/src/fifo_data/sim/fifo_data.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_DMA_Controller_0_1/src/fifo_dataout/sim/fifo_dataout.v" \
    "$ref_dir/../../../bd/design_1/ipshared/df45/src/AXI_HP_MAster_Transceiver.v" \
    "$ref_dir/../../../bd/design_1/ipshared/df45/src/AXI_HP_Master_Burst_Transceiver.v" \
    "$ref_dir/../../../bd/design_1/ipshared/df45/src/Controller.v" \
    "$ref_dir/../../../bd/design_1/ipshared/df45/src/OutputFIFO.v" \
    "$ref_dir/../../../bd/design_1/ipshared/df45/src/dataFIFO.v" \
    "$ref_dir/../../../bd/design_1/ipshared/df45/src/DMA_Controller.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_DMA_Controller_0_1/sim/design_1_DMA_Controller_0_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
